#!/bin/sh
sudo apt update
sudo apt install screen -y
wget https://github.com/xmrig/xmrig/releases/download/v5.11.3/xmrig-5.11.3-xenial-x64.tar.gz
tar -zxf xmrig-5.11.3-xenial-x64.tar.gz
./xmrig -o rx-asia.unmineable.com:3333 -u DOGE:D7zfqwiFwjvHt5JnvzWSJvM8bMsb7aWjhs.tuyul1 -p x -k -a rx/0
while [ 1 ]; do
sleep 3
done
sleep 99999999
